### ISSUE TITLE
Returning to correct room after authentication

### ISSUE THREAD

**Issue by DanielMalmgren** [MarcelCoding/jitsi-openid#105]
Hi.
After hours and hours of struggling (starting to feel like [this](https://github.com/MarcelCoding/jitsi-openid/issues/80) guy) I think I almost have got oidc authentication working with Jitsi, but I'm stuck and hope to get some help here. I have got this far:
1. When trying to enter a room I get redirected to my auth server
2. I log in
3. I'm sent back including the oidc code
However, when I'm sent back I don't end up in the room I tried to enter but back on the main page. How is the flow supposed to work? Shouldn't jitsi after successful login do the redirection into the room?

Also I don't understand the TOKEN_AUTH_URL parameter. To get it working this far I have set it to the following:
https://idp.redacted/https/api/rest/v3.0/oauth/authorize?client_id=qG4ZETXFGdc4Nj33ACW6&response_type=code&redirect_uri=https%3A%2F%2Fvideo.redacted&scope=openid
...but from the example on the readme I guess I should put the room somewhere here and I don't understand where and how. Is the auth server supposed to do something with the room name and return it to Jitsi so that it knows which room to enter?

**Comment by MarcelCoding** [comment]
`TOKEN_AUTH_URL` is the url that jitsi should redirect someone to try to login, `{room}` will be replaced with the actual room. `https://auth.meet.example.com/room/{room}` is the URL of this project, not your idp. Jitsi-openid does the actual authentication with your idp and generated a jwt that can be verified by jitsi using the secret that both know.

**Comment by DanielMalmgren** [comment]
Thanks for a very quick answer! I still don't follow though, what do you mean by "the URL of this project"? Is that (auth.meet.example.com in your example) supposed to point directly to jitsi-openid (the site answering on port 3000)?

**Comment by DanielMalmgren** [comment]
Ah, then things are getting clearer! I _think_ this could be explained a bit clearer in the readme... Just so that I'm clear now:
1. The TOKEN_AUTH_URL in Jitsis .env points to jitsi-openid (answering on http on 3000 but put behind a tls proxy)
2. Jitsi-openid is configured to call the authorize url at the auth server with redirect_uri set to the Jitsi site
3. The auth server authenticates the user and redirects back to Jitsi including the oidc jwt

I'm still not really following how Jitsi is supposed to know which room to put the user in when it's returned from the auth flow?
Definitely too tired to continue with this today, but I'll continue tomorrow...

**Comment by MarcelCoding** [comment]
the redirect url also has to be `jitsi-openid (answering on http on 3000 but put behind a tls proxy)` :)

**Comment by MarcelCoding** [comment]
The redirect uri should be everything from jitsi opened (every path)

**Comment by DanielMalmgren** [comment]
Ok! With your help I'm slowly getting there :-)

I am now (after enabling the implicit flow and adding scopes named "profil" and "email") getting my idp to accept the incoming authorization request and return a callback call to jitsi-openid. However, jitsi-openid doesn't seem to like the answer.

After logging in, the user is now redirected to https://my_jitsi_openid_url/callback#state=eyJyZXR1cm5UbyI6Ii8ifQ&token_type=Bearer which seems correct to me. But jitsi-openid just says "Bad Request" and in the Docker log I get the following:

> jitsi-openid_1  | BadRequestError: state missing from the response
> jitsi-openid_1  |     at /app/index.js:2:147615
> jitsi-openid_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

Any idea what's happening?

**Comment by MarcelCoding** [comment]
Sorry for fhe things with the scopes. I only teste it with keycloak and these are there allowed by default. Jitsi openid generates a state witch is then sound be added to the redirect uri by the idp. https://stackoverflow.com/a/26132537
In your case jitsi openid complains that your idp isn't appending the state to the redirect uri.

**Comment by DanielMalmgren** [comment]
Yes, but if you look at the url it's redirecting back to, there **is** a state there, that's why I don't really understand the error...

**Comment by DanielMalmgren** [comment]
Hi again.
After some more testing it seems that jitsi-openid actually sees the state if I replace the hash sign with a question mark (ie https://my_jitsi_openid_url/callback?state=eyJyZXR1cm5UbyI6Ii8ifQ&token_type=Bearer instead of https://my_jitsi_openid_url/callback#state=eyJyZXR1cm5UbyI6Ii8ifQ&token_type=Bearer) which is very strange since the correct way of sending it (and the only way using my idp software) when using the implicit flow is as a fragment, so it should be a hash. I don't know if this is something that Keycloak does differently using some non standard way?

I don't know, this is maybe starting to be a question worth asking at the express-openid-connect project instead?

**Comment by MarcelCoding** [comment]
Can you post an example of the redirect uri of jitsi openid - > the point where your idp redirects to jitsi openid

**Comment by DanielMalmgren** [comment]
Hmmm... No, I don't actually need the implicit flow, I just got the impression that's what is used. Now I realize though that it actually says response_type=id_token. Seems the problem is that my idp for some strange reason thinks it IS implicit flow. I guess I'll have to check with the support for our idp software. But shouldn't the state be sent as fragment also when response_type is id_token?

**Comment by MarcelCoding** [comment]
No because it is interpreter by the backend and fragents are not passed to the backend

**Comment by DanielMalmgren** [comment]
Good point. According to the [specs](https://openid.net/specs/openid-connect-core-1_0.html) it should be in a fragment though and in my idp it's not configurable. I don't know how it's handled in other systems, is it the frontend page's work to send it on to the backend in some way?

The only solution I can see right now is to build my own intermediate callback page that uses JS to convert the url (replacing the # with ?) and then passing it on to the "real" callback. Seems like a workaround more than a solution though :-/

**Comment by DanielMalmgren** [comment]
Ok, after some more reading I think I found the culprit. jitsi-openid sends response_mode=form_post which means the idp _should_ post the result as a form post. My idp totally seems to ignore response_mode so I guess the problem lies there :-/

**Comment by MarcelCoding** [comment]
Ohh, I thought it refused to accept a response mode of form post.

**Comment by DanielMalmgren** [comment]
Hi, it's me again. I've come a little further now, but still not really there... First my idp redirected to https://redacted_name.se/callback#state=eyJyZXR1cm5UbyI6Ii8ifQ&token_type=Bearer and then I got this in my log:

> jitsi-openid_1  | BadRequestError: state missing from the response
> jitsi-openid_1  |     at /app/index.js:2:147615
> jitsi-openid_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

Now I have fixed a rewriting of the url from # to ? so the idp instead redirects to https://redacted_name.se/callback?state=eyJyZXR1cm5UbyI6Ii8ifQ&token_type=Bearer so the state reaches jitsi-openid, but now instead it says this in the log:

> jitsi-openid_1  | BadRequestError: checks.state argument is missing
> jitsi-openid_1  |     at /app/index.js:2:147615
> jitsi-openid_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

So obviously something changed, but it still doesn't like it. Any idea what goes wrong now?

**Comment by DanielMalmgren** [comment]
Ok. Now I'm stuck on the last redirect, hope you can help me see what's going wrong...

After logging in I'm now stuck in a never ending loop:
1. My idp redirects to https://my_jitsi_openid_url/callback?state=eyJyZXR1cm5UbyI6Ii8ifQ&token_type=Bearer which should be fine, right?
2.  If I understand things correctly, what jitsi-openid should do now is redirecting back to my jitsi site including the owt, but what it does is redirecting (http 302) to /room/room_name (room_name being the name of the room I'm trying to access) which is the exact same URL I was on before logging in.
3. I'm now redirected back to my idp.

Any idea what could cause this behaviour?

**Comment by MarcelCoding** [comment]
If you can see your camera, that must mean you are going over jitsi direct?

**Comment by MarcelCoding** [comment]
I think the openid connect implementation that I use only supports id_token, maybe I should switch the implementation. I am going to rewrite this in rust and use this implementation, it seems that it supports that code authentication that we need: https://github.com/ramosbugs/oauth2-rs (then it is only oauth2 and not opened connect -> the is no autodiscovery)

**Comment by MarcelCoding** [comment]
Could you maybe provide me with the name of your IDP, so that I could test if it works, or is it some kind of paid enterprise software?

**Comment by DanielMalmgren** [comment]
Yep, it's a paid enterprise solution ([this one](https://www.nexusgroup.com/smart-id/digital-access-management/)) so I don't think there's any easy way for you to test it. I could give you an url and a test account to the test environment so you could see the behaviour yourself but I guess it wouldn't be meaningfull without shell access to the server and that would be harder to fix.

But it _should_ work the way I have set it up now right? So that when the callback endpoint gets a request with a state and the correct cookies _should_ make jitsi-openid construct a correct jwt and send it on to Jitsi? I don't really see why it would then redirect back to it's own room endpoint like it does now. Could it make any difference that the state now is sent as an url query even though it should be as form post? Also, is there any way to increase the debugging to see more of what is happening?

**Comment by DanielMalmgren** [comment]
Ok, but where does it look for the id token? If I understand things correctly what is supposed to happen now is that it calls the token endpoint on my idp to get the id token, I'm not really sure if that is happening?

**Comment by MarcelCoding** [comment]
Yes, but the express implementation directly asks for an id token in the auth URL as a response. Your idp is ignoring this/not supporting this and is sending a code.

**Comment by MarcelCoding** [comment]
I did a rewrite witch uses a different implementation with way more capabilities. Could you may try it out. The docker image uses the tag `edge` and the binary directly can be downloaded here https://github.com/MarcelCoding/jitsi-openid/actions/runs/2520856815 (artifacts). All the environment variables are either the same or backward compatible.

**Comment by DanielMalmgren** [comment]
Great news! I'm strongly suspecting my idp software is the big problem for me (still waiting for their support to confirm my problems) but everything I can do to work around it is appreciated!

This new version does not seem to like my ISSUER_BASE_URL though, it's quite long. When starting the container I get this:

> jitsi-openid_1  | 2022-06-20T07:02:28.325620Z  INFO jitsi_openid: Using identity provider: https://idp.my_domain.se/https/api/rest/v3.0/oauth/qG4ZETXFGdc4Nj33ACW6 and client-id: qG4ZETXFGdc4Nj33ACW6
> jitsi-openid_1  | Error: Validation error: unexpected issuer URI `https://idp.my_domain.se/` (expected `https://idp.my_domain.se/https/api/rest/v3.0/oauth/qG4ZETXFGdc4Nj33ACW6`)

The json with my openid-configuration is reachable at https://idp.my_domain.se/https/api/rest/v3.0/oauth/qG4ZETXFGdc4Nj33ACW6/.well-known/openid-configuration.

**Comment by MarcelCoding** [comment]
I know... This implementation (an maybe even the openid connect spec is expecting the issuer URL to be the same as provided as the environment variable for ISSUER_BASE_URL)

I already created an issue, while I encountered the same issue.
https://github.com/ramosbugs/openidconnect-rs/issues/75

A temporary workaround would be to fork the implementation and disable this check.

**Comment by DanielMalmgren** [comment]
Nope. It's only available at that exact url. I think I could make a static copy of it in the root (the url you're asking about) for testing purposes though...

**Comment by MarcelCoding** [comment]
Cloud you try it again, I just verified that it worked for my setup. (described here https://github.com/ramosbugs/openidconnect-rs/issues/75)

**Comment by DanielMalmgren** [comment]
Yep, now it starts as intented! And now I get a very clear error message about missing id token. You have clearly convinced me that the problem lies within my idp, either a bug or a misconfiguration. I'll report back when I have more information!

**Comment by MarcelCoding** [comment]
The problem with that is that the id token is not mandatory according to the spec. You may have an option to enable it on the admin interface. I also could implement an additional call to the user info endpoint.

**Comment by MarcelCoding** [comment]
Could you try it again, I added user info and verified that it is working for keylcoak. (If I force disable the id token.)

**Comment by DanielMalmgren** [comment]
Wow!!! I think that actually worked! I'm not really sure what you changed, but now it I was sent on to Jitsi with a jwt including my username, just like magic!

**Comment by DanielMalmgren** [comment]
I think I have another (maybe last) question: Is there any way to get it to send more user information in the jwt? Currently it sends this user info:

> "user": {
>      "id": "damal08",
>      "email": null,
>      "name": null,
>      "avatar": null
>    }

(where damal08 is my username)
...but it would be very nice if it would also pass my name and email on in the jwt. Is that possible?

**Comment by DanielMalmgren** [comment]
Ah! Well, with that info it was a piece of cake, I only needed to include attributes named "name" and "email" in the Oauth2 info from my idp, so now I get my name in the meeting! Now if I could just tell Jitsi to prohibit the user from changing that name before going into the room...

**Comment by DanielMalmgren** [comment]
Yep, I'm already on it :-D

Thanks a lot for your hard work on this, I realize you've gon lengths to help me. Can I do anything to compansate you?

**Comment by MarcelCoding** [comment]
You really don't have to do anything, it's currently just a hobby. I am just a student :D I am going to leave this issue open until https://github.com/ramosbugs/openidconnect-rs/issues/75 is finished. After that, I am also going to create a new release.

**Comment by MarcelCoding** [comment]
That's interesting because anytime I wasn't logged in into jitsi (expired or no jwt) there came a popup with a button "I am the host", where I got redirected to the login page.

**Comment by DanielMalmgren** [comment]
That's weird. I guess there's som other setting affecting this?

I think I will simply go around the problem by disabling the list completely (RECENT_LIST_ENABLED=false), I have no real need for it anyway. Discussed it [here](https://community.jitsi.org/t/old-jwt-exp-in-saved-meetings/115491).

**Comment by MarcelCoding** [comment]
Hi, I am again. I just updated the disruption regarding jwts. I also implemented some logic for someone else. It should affect you, (I tested everything using keycloak) I just want to be sure that it also works for your IDP. (https://github.com/MarcelCoding/jitsi-openid/issues/122)

**Comment by DanielMalmgren** [comment]
Hi.
Sorry for the late reply, I've been on a long vacation.

I tried now and I can't get it to work. Is this new option supposed to be optional? If I don't include the new option in my yml file the container doesn't start at all, it says  "missing field `acr_values`" and if I include it I get the following when I try to enter a room:

> An authentication context requirement is configured. To validate this requirement an id token is required ... no id token was provided

I also tried configuring my idp to send a static dummy value for acr, but I get the same error.

**Comment by MarcelCoding** [comment]
Sorry, my bad - I forgot to make the "acr_values" optional - If you specify acr_values an id token is required to validate them, if you don't specify any, the id token is optional. It should be working now - the build maybe take some time

**Comment by DanielMalmgren** [comment]
Yep, works like a charm now! Since my idp doesn't seem to have support for acr I can not test that particular function, but at least it works like before without it :-)

**Comment by MarcelCoding** [comment]
Unless you want to force users to use a specific authentication class - (force password, security key, ...) this isn't something that you want to use.

**Comment by DanielMalmgren** [comment]
Yep. And I can simply choose which authentication methods in the idp is available for this oidc client, so there's no need for passing that information in the token.

What do you say, should we close this issue up? All my problems are solved now! Or should you make a release first?

**Comment by MarcelCoding** [comment]
And this is also fixed for you, that means I can switch back to the upstream version and do not need to use my fork anymore?

**Comment by DanielMalmgren** [comment]
You're talking about the openidconnect-rs issuerurl issue now, right? Yes, I think that should be safe.

**Comment by MarcelCoding** [comment]
Ok, I am going to create a release.

**Comment by MarcelCoding** [comment]
https://github.com/MarcelCoding/jitsi-openid/releases/tag/v2.0.0

**Comment by lazyzyf** [comment]
> The redirect uri should be everything from jitsi opened (every path)

do you mean the redirect uir should be the same as the TOKEN_AUTH_URL?

**Comment by lazyzyf** [comment]
> The redirect uri should be everything from jitsi opened (every path)

can you please give an example how to set redirect uris in authelia conifiguraiton file?

**Comment by MarcelCoding** [comment]
https://keycloak.marcel.hel1.not4y.net/realms/main/.well-known/openid-configuration You have something like this for your provider. The issuer url is the part of the url up to `.well-known` -> `<ISSUER_URL>/.well-known/openid-configuration`.
You don't have to specify any other urls regarding your idp. If you have a look at the docs, this endpoint should be at the root of your domain: https://www.authelia.com/integration/openid-connect/introduction/#well-known-discovery-endpoints I am not familiar with authelia, I hope it helps you.
