### ISSUE TITLE
Empty string as name

### ISSUE THREAD

**Issue by DanielMalmgren** [MarcelCoding/jitsi-openid#147]
Hi.
I'm struggling with another really strange problem. For some of my users the jwt end up having an empty string as name. I have been digging deep into the problem and established that these users get given_name and family_name in their openid userinfo like everybody else, I can't seem to find any difference between the users that work and those that don't.

Questions:
1. Can you see ANY scenario that would end up with an empty name?
2. Is there any way of increasing log output to be able to actually follow what's happening under the hood?

This is what the decoded data portion of the jwt looks like for these users:
{
  "context": {
    "user": {
      "id": "5i55fx32r9mo",
      "email": "dummy@example.org",
      "affiliation": null,
      "name": "",
      "avatar": null
    },
    "group": null
  },
  "aud": "jitsi",
  "iss": "jitsi",
  "sub": "*",
  "room": "*",
  "iat": 1662698372,
  "exp": 1662784772
}

**Comment by DanielMalmgren** [comment]
Sorry, you can safely ignore me. After some more hours of debugging it turns out that this (once again) is a bug in my idp, it simply omits some of the userinfo in some calls. However, if you ever feel you want to add anything more code, a log level setting would be wonderful, flooding my log with details for cases like this :-)

**Comment by MarcelCoding** [comment]
Sure I can add more optional logging, but I don't quite know what had helped here? The user info returned by the idp would be the only thing that would sound reasonable to me.

**Comment by MarcelCoding** [comment]
Or the reason a specific value was chosen?

**Comment by DanielMalmgren** [comment]
Yes, I guess the values returned by the idp would be nice. And maybe if it would be possible to get how it was sent, if it was in and id token or if it was fetched via the userinfo endpoint. Currently struggling to understand exactly what my idp does, it doesn't seem to send all info it should in the id token, but only under some circumstances...
