### ISSUE TITLE
support aarch64 platform

### ISSUE THREAD

**Issue by lazyzyf** [MarcelCoding/jitsi-openid#182]
do you have any plan to support arm64 platform in docker?

**Comment by MarcelCoding** [comment]
Ohh sorry, I did not noticed that with the release of v2 arm64 went missing. I'll add it again.

**Comment by MarcelCoding** [comment]
Now there is arm64 back: 
![image](https://user-images.githubusercontent.com/34819524/218299472-c53c34cf-1a0a-4819-b276-a380a7b6dabe.png)
