### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by KodoGit** [MarcelCoding/jitsi-openid#215]
Docker-compose version could be lowered. I my case 3.5 was ok without any change in formating.

If found it hard to get what is TOKEN_AUTH_URL=https://auth.meet.example.com/room/{room}

https://auth.meet.example.com part can be anything. Like https://jitsi.example.com:9999
But '/room/{room}' part must exist.
If this adapter and id provider are set up properly https://jitsi.example.com:9999/room/anything should redirect to provider and back to Jitsi.
And modern browsers can interfere in redirections changing http to https so it is highly recomended to setup reverse proxy with SSL for this container.

**Comment by MarcelCoding** [comment]
Fixed by https://github.com/MarcelCoding/jitsi-openid/commit/71e0284e6948690b33efe0dd45fd45c67e0f11f6
