### ISSUE TITLE
Avatar URL not working

### ISSUE THREAD

**Issue by KodoGit** [MarcelCoding/jitsi-openid#218]
I've added ldap mapping to my Keycloak and it returnes payload with "picture": "https://server.domain.com/photo/p01.11.jpg"
Container is pulled and recreated. Don't know how to check version for sure.
But Jitsi still receives token with "avatar": null

Avatar from Rocketchat token works.

**Comment by MarcelCoding** [comment]
How did you configure Keycloak? I currently only pull the picture from the data returned by the user info endpoint and NOT the ID token.

**Comment by KodoGit** [comment]
I've checked both userinfo and token by curl. They both have "picture". But Jitsi recives JWT with "avatar": null. 
I check JWT in chrome ctrl+shift+i ->application->storage->local storage. 
Features/recent-list there includes URL with JWT which can be decrypted using https://jwt.io/ or else.

May be there is some mistakes in this construction or image is not updated?
`    avatar: claims
        .picture()
        .and_then(|x| x.get(None))
        .map(|x| x.to_string()),`

**Comment by MarcelCoding** [comment]
Sorry, I was a bit distracted yesterday. I've forgotten to create a release: https://github.com/MarcelCoding/jitsi-openid/releases/tag/v2.0.4


If your IDP provides a ID token (Keycloak does), I don't query the user info. But I've only implemented the avatar logic to user info. Now with 2.0.4, it is also implemented to the id token parsing. I am really sorry, it was my bad.

**Comment by KodoGit** [comment]
It works! You are awesome :P
