### ISSUE TITLE
Join required again after SSO Login 

### ISSUE THREAD

**Issue by madduck** [MarcelCoding/jitsi-openid#239]
Hey, first thanks for your great plugin, it works very well for our small team of 13 with Authentik as the SSO-provider.

One of the two (minor) issues we're having is that after a user chooses to become moderator and completes the SSO dance, they are sent back to the pre-meeting screen, thus having to click "Join" again. That is mildly annoying, but not really a problem. Just thought I'd raise it here.

Best,
m

**Comment by MarcelCoding** [comment]
Hi, thanks for the feedback. Unfortunately, I am currently not able to test this out. The Jitsi instance I've originally developed this for does not exists anymore. So I don't currently have a Jitsi with access for testing. Maybe, I am deploying a small docker setup and testing this out, but don't expect it in the next few days.

**Comment by MarcelCoding** [comment]
VM's are not the problem, I have a proxmox with enough spare resources. But I have to do the setup with like keycloak, jitsi and so on. I currently started a project with some friends where a Jitsi instance is probably beeing deployed - with keycloak. So there should be a chance to test this out, But as I said, not in the near future.

**Comment by small1** [comment]
#254 is a fix for this issue :)

**Comment by MarcelCoding** [comment]
fixed in https://github.com/MarcelCoding/jitsi-openid/commit/33fadd6d46a482d34cdee133c2ba41c6820a8dc1
