### ISSUE TITLE
SSO-Login causes link with '/' to be shortened

### ISSUE THREAD

**Issue by madduck** [MarcelCoding/jitsi-openid#240]
Hey, first thanks for your great plugin, it works very well for our small team of 13 with Authentik as the SSO-provider.

The other of the two (minor) issues we're having is that while Jitsi allows us to use links like `https://jitsi/foo/bar`, after the SSO dance, `/foo` is stripped and the new moderator joins a room `bar`, which is not the same as the room `foo/bar`, and can lead to a lot of confusion.

**Comment by MarcelCoding** [comment]
Hi, thanks for your feedback. It should not be possible to use slashes in room names: https://github.com/MarcelCoding/jitsi-openid/releases/tag/v2.0.5

**Comment by madduck** [comment]
Excellent, and thanks for the massively fast turnaround!

**Comment by madduck** [comment]
@MarcelCoding

![image](https://github.com/MarcelCoding/jitsi-openid/assets/195073/c2f13c21-0d0f-4e79-a34f-ff4567f2798b)

♥

**Comment by MarcelCoding** [comment]
Very nice

**Comment by MarcelCoding** [comment]
Hi, if you deploy using docker v2.0.5 is sadly broken. I did not specify the base Image specific enough and got an implicit update to Debian bookwork with made the glibc versions incorrect. v2.0.6 https://github.com/MarcelCoding/jitsi-openid/issues/241 fixes it.
