### ISSUE TITLE
Last image tag 2.0.5 broken

### ISSUE THREAD

**Issue by cyrinux** [MarcelCoding/jitsi-openid#241]
Hi,

Thanks for this software,
FYI, the last tag 2.0.5 is broke

```jitsi-jitsi-openid-1  | 2023-10-16T09:34:15.867128501Z /jitsi-openid/jitsi-openid: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /jitsi-openid/jitsi-openid)```

**Comment by MarcelCoding** [comment]
Hi, thanks for the report! I've updated the base image in https://github.com/MarcelCoding/jitsi-openid/releases/tag/v2.0.6. With this version, it is working.
