### ISSUE TITLE
Invalid code on authorization

### ISSUE THREAD

**Issue by small1** [MarcelCoding/jitsi-openid#252]
I'm implementing this against an idp.  And we get as far as invalid code. It looks like it does fetch the token. But directly after says invalid code. 

Ir is not clear on why it fails. We can see on the IDP that it seems to have fetched the token. And the token seems correct when we test it.

**Comment by MarcelCoding** [comment]
Hi, thanks for the usage. I've seen a similar issue in the past, but wasn't able to resolve it. IDK why I didn't do it till yet, but I've added warn logging for these errors, with hopefully more details.

I have releases [2.0.7](https://github.com/MarcelCoding/jitsi-openid/releases/tag/v2.0.7) the Docker Images and binaries should be available in about 1h. Could you please deploy this version and provide me with the details of the console?

**Comment by small1** [comment]
This is what i get in the console:

`2023-10-30T20:01:30.457926Z  WARN jitsi_openid::routes: Authentication failed, Invalid Code: Parse(Error { path: Path { segments: [] }, original: Error("expected value", line: 1, column: 1) }, [60, 33, 100, 111, 99, 116, 121, 112, 101, 32, 104, 116, 109, 108, 62, 60, 104, 116, 109, 108, 32, 108, 97, 110, 103, 61, 34, 101, 110, 34, 62, 60, 104, 101, 97, 100, 62, 60, 116, 105, 116, 108, 101, 62, 72, 84, 84, 80, 32, 83, 116, 97, 116, 117, 115, 32, 52, 48, 48, 32, 226, 128, 147, 32, 66, 97, 100, 32, 82, 101, 113, 117, 101, 115, 116, 60, 47, 116, 105, 116, 108, 101, 62, 60, 115, 116, 121, 108, 101, 32, 116, 121, 112, 101, 61, 34, 116, 101, 120, 116, 47, 99, 115, 115, 34, 62, 98, 111, 100, 121, 32, 123, 102, 111, 110, 116, 45, 102, 97, 109, 105, 108, 121, 58, 84, 97, 104, 111, 109, 97, 44, 65, 114, 105, 97, 108, 44, 115, 97, 110, 115, 45, 115, 101, 114, 105, 102, 59, 125, 32, 104, 49, 44, 32, 104, 50, 44, 32, 104, 51, 44, 32, 98, 32, 123, 99, 111, 108, 111, 114, 58, 119, 104, 105, 116, 101, 59, 98, 97, 99, 107, 103, 114, 111, 117, 110, 100, 45, 99, 111, 108, 111, 114, 58, 35, 53, 50, 53, 68, 55, 54, 59, 125, 32, 104, 49, 32, 123, 102, 111, 110, 116, 45, 115, 105, 122, 101, 58, 50, 50, 112, 120, 59, 125, 32, 104, 50, 32, 123, 102, 111, 110, 116, 45, 115, 105, 122, 101, 58, 49, 54, 112, 120, 59, 125, 32, 104, 51, 32, 123, 102, 111, 110, 116, 45, 115, 105, 122, 101, 58, 49, 52, 112, 120, 59, 125, 32, 112, 32, 123, 102, 111, 110, 116, 45, 115, 105, 122, 101, 58, 49, 50, 112, 120, 59, 125, 32, 97, 32, 123, 99, 111, 108, 111, 114, 58, 98, 108, 97, 99, 107, 59, 125, 32, 46, 108, 105, 110, 101, 32, 123, 104, 101, 105, 103, 104, 116, 58, 49, 112, 120, 59, 98, 97, 99, 107, 103, 114, 111, 117, 110, 100, 45, 99, 111, 108, 111, 114, 58, 35, 53, 50, 53, 68, 55, 54, 59, 98, 111, 114, 100, 101, 114, 58, 110, 111, 110, 101, 59, 125, 60, 47, 115, 116, 121, 108, 101, 62, 60, 47, 104, 101, 97, 100, 62, 60, 98, 111, 100, 121, 62, 60, 104, 49, 62, 72, 84, 84, 80, 32, 83, 116, 97, 116, 117, 115, 32, 52, 48, 48, 32, 226, 128, 147, 32, 66, 97, 100, 32, 82, 101, 113, 117, 101, 115, 116, 60, 47, 104, 49, 62, 60, 104, 114, 32, 99, 108, 97, 115, 115, 61, 34, 108, 105, 110, 101, 34, 32, 47, 62, 60, 112, 62, 60, 98, 62, 84, 121, 112, 101, 60, 47, 98, 62, 32, 83, 116, 97, 116, 117, 115, 32, 82, 101, 112, 111, 114, 116, 60, 47, 112, 62, 60, 112, 62, 60, 98, 62, 77, 101, 115, 115, 97, 103, 101, 60, 47, 98, 62, 32, 66, 97, 100, 32, 82, 101, 113, 117, 101, 115, 116, 60, 47, 112, 62, 60, 112, 62, 60, 98, 62, 68, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 60, 47, 98, 62, 32, 84, 104, 101, 32, 115, 101, 114, 118, 101, 114, 32, 99, 97, 110, 110, 111, 116, 32, 111, 114, 32, 119, 105, 108, 108, 32, 110, 111, 116, 32, 112, 114, 111, 99, 101, 115, 115, 32, 116, 104, 101, 32, 114, 101, 113, 117, 101, 115, 116, 32, 100, 117, 101, 32, 116, 111, 32, 115, 111, 109, 101, 116, 104, 105, 110, 103, 32, 116, 104, 97, 116, 32, 105, 115, 32, 112, 101, 114, 99, 101, 105, 118, 101, 100, 32, 116, 111, 32, 98, 101, 32, 97, 32, 99, 108, 105, 101, 110, 116, 32, 101, 114, 114, 111, 114, 32, 40, 101, 46, 103, 46, 44, 32, 109, 97, 108, 102, 111, 114, 109, 101, 100, 32, 114, 101, 113, 117, 101, 115, 116, 32, 115, 121, 110, 116, 97, 120, 44, 32, 105, 110, 118, 97, 108, 105, 100, 32, 114, 101, 113, 117, 101, 115, 116, 32, 109, 101, 115, 115, 97, 103, 101, 32, 102, 114, 97, 109, 105, 110, 103, 44, 32, 111, 114, 32, 100, 101, 99, 101, 112, 116, 105, 118, 101, 32, 114, 101, 113, 117, 101, 115, 116, 32, 114, 111, 117, 116, 105, 110, 103, 41, 46, 60, 47, 112, 62, 60, 104, 114, 32, 99, 108, 97, 115, 115, 61, 34, 108, 105, 110, 101, 34, 32, 47, 62, 60, 104, 51, 62, 65, 112, 97, 99, 104, 101, 32, 84, 111, 109, 99, 97, 116, 60, 47, 104, 51, 62, 60, 47, 98, 111, 100, 121, 62, 60, 47, 104, 116, 109, 108, 62])`

**Comment by MarcelCoding** [comment]
Thanks, if I decode the bytes to a string, i get the following:

```html
<!doctype html>
<html lang="en">
   <head>
      <title>HTTP Status 400 – Bad Request</title>
      <style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style>
   </head>
   <body>
      <h1>HTTP Status 400 – Bad Request</h1>
      <hr class="line" />
      <p><b>Type</b> Status Report</p>
      <p><b>Message</b> Bad Request</p>
      <p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p>
      <hr class="line" />
      <h3>Apache Tomcat</h3>
   </body>
</html>
```

Which looks like either the user info endpoint or the token endpoint is not working.

**Comment by small1** [comment]
Strange. We tested with a small python script and we did get a correct response.  And the idp also checks the request as done.  Ill get back to the IDP  specialist.

**Comment by MarcelCoding** [comment]
Idk it says Bad Request which indicates that the client is doing something wrong, but maybe the idp is just not spec compliant, because it works correctly with keycloak and also people reported it is working with Nextcloud and authentic.

**Comment by small1** [comment]
We found that we got that when using a test user not correctly entered in the system.  When we use a real user we get this: 

 original: Error("Failed to parse payload JSON: Error(\"invalid type: sequence, expected a string\", line: 1, column: 299)", line: 7, column: 1) }

I can email the rest of the log since it contains a jwt i dont want to paste it here.

**Comment by MarcelCoding** [comment]
Sure, please send it to me@m4rc3l.de

**Comment by small1** [comment]
We might have found something. Can you add en option to change the scope?  The idp defaults might send out stuff we cant accept. But the defaults is in use by quite a few applications in prod.  so if we could ask for a custom scope or scopes that might help a bit.

**Comment by small1** [comment]
I sent an email with the log.

**Comment by MarcelCoding** [comment]
Resolved in email.
