### ISSUE TITLE
Skip pre join screen after auth

### ISSUE THREAD

**Issue by MarcelCoding** [MarcelCoding/jitsi-openid#254]
> We have the prejoin screen enabled.  When we are authenticated we want to disable that screen.
>
>You can do it when you send the url to jitsi with adding `#config.prejoinConfig.enabled=false` to the url part. (there are quite a few options you can send along that way to also enable/disable buttons and more)
>
>So we share the link to the room and we get to a prejoin screen. On that we have a button that will send you to the auth screen (Instead of using the i am moderator popup) and then you get back to the room.  IF we can specify that extra part in the url  you get straight in. As it is right now you get back to the prejoin page.

Email from @small1

**Comment by MarcelCoding** [comment]
@small1 could you please try it. The pre join screen should now be skipped by default: https://github.com/MarcelCoding/jitsi-openid/releases/tag/v2.0.10

**Comment by small1** [comment]
@MarcelCoding first Test wad successful!  I will do some better tests tomorrow to be safe :)

**Comment by madduck** [comment]
It works for us too. This also fixes #239 …

**Comment by MarcelCoding** [comment]
As @small1 did not write anything further, I'll consider this fixed in https://github.com/MarcelCoding/jitsi-openid/commit/33fadd6d46a482d34cdee133c2ba41c6820a8dc1.
