### ISSUE TITLE
Group in context is null

### ISSUE THREAD

**Issue by nwinkelstraeter** [MarcelCoding/jitsi-openid#261]
Hello,

I am currently trying to get recordings in jitsi working with a proper participants list in the metadata.json that jibri creates.
This requires the mod_presence_identity prosody plugin to be enabled. (https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#retrieve-token-identifiers-data)

That plugin does not accept any null values in the context and just crashes.  (See note at the end of the linked paragraph).

I use this with authentik and it does send an affiliation or avatar. I fixed this simply by setting some dummy values using a custom scope mapping and adding that scope to the `SCOPES` variable.

However it looks like the `groups` value is always set to  `None` [here](https://github.com/MarcelCoding/jitsi-openid/blob/33fadd6d46a482d34cdee133c2ba41c6820a8dc1/src/routes.rs#L323). So I can't set it with a scope mapping.

I tried simply removing `group` from the context and everything still works and mod_presence_identity does not crash anymore. Yay :D

I see that groups are part of jitsi expected [token structure](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#token-identifiers-structure-optional), though.
So while just removing them works, a way to somehow influence the value of `group` would be nice. Maybe with in environment variable or with with the IDP somehow.

Thanks, this project is really helpful. :)

**Comment by MarcelCoding** [comment]
So what would you prefer? Using an environment variable or extracting it from the id token/user info?

**Comment by nwinkelstraeter** [comment]
I would be fine with just an environment variable as I just want to set a dummy value that is not null.
But others might want to use it for reporting/analytics, in that case extracting it from user info is probably more useful.
