### ISSUE TITLE
Nbf prop missing in token

### ISSUE THREAD

**Issue by chief-nerd** [MarcelCoding/jitsi-openid#264]
My self-hostec jitsi requires the property nbf to be set in the token. Otherwise it fails. 

```
Sorry, you’re not allowed to join this call. Possible reasons: Invalid `nbf` value. 
```

If I edit the token manually and add nbf with the same value is iat, then it works. 

Jitsi Version: stable-8138-1

**Comment by MarcelCoding** [comment]
Should be fixed in https://github.com/MarcelCoding/jitsi-openid/actions/runs/7097816522
https://github.com/MarcelCoding/jitsi-openid/releases/tag/v2.0.12

**Comment by chief-nerd** [comment]
Awesome! Will try and report back (and close issue)

**Comment by chief-nerd** [comment]
Awesome it works now! (also testet on old stable and newest stable version)

Now I only have the problem of Guest vs/ Moderator access. But I create a new Issue for that: https://github.com/MarcelCoding/jitsi-openid/issues/265
