### ISSUE TITLE
Missing "moderator": "true" prop from claim

### ISSUE THREAD

**Issue by chief-nerd** [MarcelCoding/jitsi-openid#265]
on the latest jitsi image the JWT token requires the 
`"isModerator": true` prop to be set in case guest are allowed.
(a Moderator has to join first, then the guest can)

My ID (authentik) can provide that prop in the claim, but it needs to be passed on to the JWT.

--- 
... Ideally I generic solution can be found for future props.
Like take all the props in the claim and pass them on.
This would also allow to set e.g. avatar etc pp

```
{
    "context": {
        "user": {
            "avatar": "https://robohash.org/user1",
            "name": "user1",
            "email": "user1"
        }
    },
    "moderator": true,
    "aud": "jitsi",
    "iss": "5bX...",
    "sub": "meet.jitsi",
    "room": "*",
    "iat": 1701859693
    "nbf": 1701859693
    "exp": 1701859693
}
```

**Comment by chief-nerd** [comment]
It's per user base. I would not be feasible if everyone on the call would be a moderator :/

I think the best way would just be to merge the claim object into the jwt and add iat, nbf, etc to it. That way it can stay compatible for a long time. 

I would be happy to contribute code myself, but my Rust is a little rusty.

**Comment by MarcelCoding** [comment]
Could you try out https://github.com/MarcelCoding/jitsi-openid/commit/799d44543864b8173d21da03091c48d7519694c4? it is published as a docker tag as `edge`. All remaining properties from the idp are now being passed to jitsi.

**Comment by chief-nerd** [comment]
Tried it real quick: does NOT work yet .... will spend more time tomorrow to do a deeper test / debugging.
No seeing the new props at all.

**Comment by MarcelCoding** [comment]
Are you able to add the moderator flag to the claims. Unfortunately I am not able to extract properties from the root of the token that are not openid spec conform.

**Comment by chief-nerd** [comment]
I checked out the docs again ... the JWT above is not correct (you were right)
The moderator flag is somewhere else:

```
{
  "context": {
    "user": {
      "id": "2b2b0...",
      "email": "user@domain",
      "name": "Jakob",
      "avatar": null,
      "moderator": "true
    },
    "group": ""
  },
  "aud": "jitsi",
  "iss": "jitsi",
  "sub": "'*'",
  "room": "*",
  "nbf": 1702307828,
  "iat": 1702307828,
  "exp": 1702394228
}
```
So my claim would return:
![Screenshot 2023-12-11 at 16 17 38](https://github.com/MarcelCoding/jitsi-openid/assets/9266151/c7504724-f2ce-4f87-90df-f75fc1af6626)

However that is not reflected in the JWT :(

**Comment by MarcelCoding** [comment]
Ok, idk why it did not work. I've added it hard-coded just as with affiliation: https://github.com/MarcelCoding/jitsi-openid/releases/tag/v2.0.13

**Comment by chief-nerd** [comment]
Ok, happy to test once the docker image was compiled.

**Comment by chief-nerd** [comment]
OK I see the property now - great!
However it's still `null` all the time ... so now I need to figure out how to return the right `claims.additional_claims()` property. Any idea?

**Comment by chief-nerd** [comment]
If I set it manually to `true` it works completely -- so that is at least light at the end of the tunnel :)

**Comment by chief-nerd** [comment]
OK so I verified the moderator property is correct in my JWT from the authentik:
```
{
    "iss": "https://id.domain.com/application/o/jitsi/",
    "sub": "2b2b04b...",
    "aud": "juOJ0...",
    "exp": 1702335563,
    "iat": 1702333763,
    "auth_time": 1702333763,
    "acr": "goauthentik.io/providers/oauth2/default",
    "amr": [
        "pwd"
    ],
    "email": "user@domain.com",
    "email_verified": true,
    "picture": "https://secure.gravatar.com/avatar/...",
    "moderator": true,
    "name": "J",
    "given_name": "J",
    "preferred_username": "j",
    "nickname": "j",
    "groups": [
        "authentik Admins"
    ]
}
```

**Comment by chief-nerd** [comment]
@MarcelCoding I checked now everything on the ipd site. Everything is correct.

Possibly a
`.map(|moderator| moderator.to_string())`
is missing here https://github.com/MarcelCoding/jitsi-openid/blob/main/src/routes.rs#L280

I always get `null`! and null is suspicious ...
(Also for affiliation ... but I dont need that, so I dont care)

Can you test? Maybe add logs? Those infos are anyway "public" in the jwt token

**Comment by MarcelCoding** [comment]
That `affiliation` is not working is strange, because it worked in the past... (https://github.com/MarcelCoding/jitsi-openid/issues/114) @DanielMalmgren could you check if the `affiliation` is still working for you with the lasted version?

**Comment by chief-nerd** [comment]
Had a little time to look again into this ...
Update to authentik 2024.2.2 --> it works now magically. .... except #290 :D

But the moderator issue can be closed, as it's working.

**Comment by chief-nerd** [comment]
For Documentation:

With Authentik 2024.02
Property Mapping
Scope: `jitsi.moderator`
```
return { "moderator": request.user.attributes.get("jitsi.moderator", False) }
```

And in the config:
```
- SCOPES=email jitsi.name jitsi.moderator jitsi.avatar
```
