### ISSUE TITLE
Trying to work with Authelia

### ISSUE THREAD

**Issue by dacrudg** [MarcelCoding/jitsi-openid#316]
Hi,

I'm trying to get this to work with Authelia.
Authelia requires a configuration like:

### Jitsi
- client_id: 'jitsi'
        client_name: 'Jitsi'
        client_secret: $pbkdf2-sha512$310000$yjRam/tJ2Jwv122W0gtbzg$yTadtJmRuJxBwd.m4Wmm3itwA6cP.b7C3/q.F3Qx1Tw5XZTHK2j38ADve9KL5uRnW9xXMMBAan0PPjfV/4.SiA
        public: false
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://jitsiopenid.domain.com/user/oauth2/Authelia/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'

What value would I set for 'redirect_uris' in the example above? Any help would be much appreciated.  Thank you
Here's an example of a Gitea configuration: https://www.authelia.com/integration/openid-connect/gitea/

**Comment by qvalentin** [comment]
I guess this just has to be 'https://jitsiopenid.domain.com/callback'.

**Comment by qvalentin** [comment]
I can confirm it is working with authelia, here is the full config:

```nix
clients = [
  {
    client_id = "jitsi";
    client_name = "Jitsi";
    client_secret = "REDACTED";
    public = false;
    redirect_uris = [ "https://auth-meet.example.com/callback" ];
    scopes = [
      "openid",
      "email",
      "profile"
    ];
    authorization_policy = "one_factor";
    userinfo_signed_response_alg = "none";
    token_endpoint_auth_method = "client_secret_basic";
  }
];
```
