### ISSUE TITLE
No idea how to use this

### ISSUE THREAD

**Issue by boredomdenied** [MarcelCoding/jitsi-openid#80]
Documentation is quite sparse and assumes a lot. There appears to be numerous variations in how to setup jitsi. What are the prereqs for this to work? I see no JWT anything digging through config files on a standard jitsi install. Is this some add-on? What are the additional subdomains referring to? I have a vanilla instance with zero subdomains that seems to be working out.

Having said all of that, I have no idea how to use this whatsoever. Please help me figure this out so I can send a PR to update the readme so other users don't get lost. Thank you

**Comment by MarcelCoding** [comment]
The README is based on a [jitsi setup using docker](https://github.com/jitsi/docker-jitsi-meet). The references to jitsi e.g. the [`docker-compose.yaml`](https://github.com/MarcelCoding/jitsi-openid#docker-compose ) are pointing to the [`.env`](https://github.com/jitsi/docker-jitsi-meet/blob/master/env.example) from jitsi. Basically you have to change the values defined [here](https://github.com/MarcelCoding/jitsi-openid#jitsi-configuration) in the `.env` from jitsi.

In other words `JITSI_SECRET` should be the same as `JWT_APP_SECRET` at the .env from jitsi and `JITSI_SUB` the same as `JWT_APP_ID`.

The value `ISSUER_BASE_URL` is the base URL of your ID Provider. (`${ISSUER_BASE_URL}/.well-known/openid-configuration` should result in something like [a](https://id.til-pockrandt.de/auth/realms/pockrandt/.well-known/openid-configuration) or [google](https://accounts.google.com/.well-known/openid-configuration))
`CLIENT_ID` and `SECRET` is your OpenID Client ID and Secret.
And as last you have to update all URLs.
